apiVersion: v1
kind: Service
metadata:
  name: ritu-portfolio
spec:
  selector:
    app: ritu-portfolio
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ritu-portfolio
spec:
  selector:
    matchLabels:
      app: ritu-portfolio
  replicas: 3
  template:
    metadata:
      labels:
        app: ritu-portfolio
    spec:
      containers:
        - name: ritu-portfolio
          image: <docker-image-name>
          ports:
            - name: http
              containerPort: 3000
